version: '3.9'
services:
  doc-app:
    build: .
    container_name: doctor_rec_container
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --proxy-headers
    networks:
      - doc_network
    restart: unless-stopped
    volumes:
      - doc_data:/app/chroma_db
    environment:
      - FORWARDED_ALLOW_IPS=*

networks:
  doc_network:
    driver: bridge

volumes:
  doc_data:
    external: false
  doc_logs:
    external: false
  doc_chroma:
    external: false